/**
 * Reference system types.
 *
 * FileReference: the data stored per file-page relationship.
 * ReferenceMap: the full in-memory index, keyed by pageId.
 *
 * Designed to serialize directly to JSON — no classes, no methods.
 */

export interface FileAnnotation {
  id: string;
  text: string;
  createdAt: string;
}

export interface FileReference {
  refId: string;           // unique id for this reference instance
  fileId: string;          // matches FileEntry.id in the file library
  filePath: string;        // absolute path — source of truth
  fileName: string;
  fileType: 'image' | 'pdf' | 'video' | 'audio' | 'document' | 'other';
  thumbnailPath?: string;  // generated by main process
  size: number;
  addedToPageAt: string;   // ISO — when it was referenced in this page
  annotations: FileAnnotation[];

  // Relationship metadata
  pageId: string;
  bookId: string;
}

/**
 * ReferenceMap: pageId -> FileReference[]
 *
 * Also maintains an inverse index: fileId -> pageId[]
 * so we can answer "which pages reference this file?" in O(1).
 */
export interface ReferenceMap {
  byPage: Record<string, FileReference[]>;
  byFile: Record<string, string[]>;  // fileId → pageIds
}
