/**
 * File Library types.
 *
 * FileEntry represents a referenced file — never a copy.
 * The `path` field is the absolute path on the user's filesystem.
 * `thumbnailPath` is generated by the main process and cached locally.
 */

export type FileType = 'image' | 'pdf' | 'video' | 'audio' | 'document' | 'other';

export interface FileEntry {
  id: string;
  name: string;
  path: string;            // absolute path on disk — reference only
  thumbnailPath?: string;  // cached thumbnail generated by main process
  type: FileType;
  size: number;            // bytes
  folderId: string | null;
  addedAt: string;         // ISO — when it was referenced, not created
  tags: string[];
}

export interface Folder {
  id: string;
  name: string;
  parentId: string | null;
  color?: string;
}
